name: mighty_personal_blog
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Basic
  cupertino_icons: ^1.0.4
  cached_network_image: ^3.2.1
  google_fonts: ^3.0.1
  intl: ^0.17.0
  syncfusion_flutter_pdfviewer: ^20.3.47

  #UI
  flutter_staggered_animations: 1.0.0
  rounded_loading_button: ^2.1.0
  carousel_slider: ^4.1.1

  # Firebase
  firebase_core: ^2.4.0
  firebase_analytics: ^10.0.7
  firebase_crashlytics: ^3.0.7
  firebase_auth: ^4.2.0

  #login
  google_sign_in: ^5.3.2
  the_apple_sign_in: ^1.1.1
  otp_text_field: ^1.1.3
  country_code_picker: ^2.0.2

  # ADS
  google_mobile_ads: ^1.2.0
  facebook_audience_network: ^1.0.1

  #Network
  http: ^0.13.4
  connectivity_plus: ^2.3.2

  #State Management
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1

  #One Signal
  onesignal_flutter: ^3.3.1

  #Video Player
  video_player: ^2.4.2

  #Other
  html: ^0.15.0
  flutter_html: ^2.2.1
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  flutter_vector_icons: ^1.0.0
  package_info_plus: ^1.4.2
  url_launcher: ^6.1.2
  share_plus: ^4.0.5
  image_picker: ^0.8.5+3
  webview_flutter: ^2.0.4
  translator: ^0.1.7
  flutter_tts: ^3.4.0
  flutter_pollfish: ^4.0.7
  story_view: ^0.13.2
  lottie: ^1.3.0
  photo_view: ^0.14.0

  #Localization
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/BAT2023ICON.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/BAT2023ICON.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/BAT2023ICON.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/BAT2023ICON.png"
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Flag/

